### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by maureennaval** [hmc-godaddy-clinic-16/editor-section#15]
Add descriptions for input fields

- Need to sync with Josh about how we want to go about doing this with the new layout that vNetx is moving towards

**Comment by Koverbay** [comment]
After discussion with Heidi, we will probably want to get rid of the description for the dates and only keep a single description of the general announcement at the top of the editor. We will also put in "filler text" into the input boxes, so that the user knows what is supposed to go in each. This aligns with GoDaddy's current style.
